language: python
sudo: false
python:
  - pypy
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - '3.10'

install:
  - pip install -e .
  - pip install ipaddress six
  - pip install -r requirements-tests.txt
  - git submodule init && git submodule update

script:
  - py.test tests
